name: Lint

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.18.1

      - name: Install dependences
        uses: bahmutov/npm-install@HEAD

      - name: Run Lint
        run: yarn lint --quiet
